name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - test

env:
  PROJECT_ID: ${{ secrets.SECRETS_GCP_PROJECT_ID }}
  GKE_CLUSTER: example-autopilot-cluster    # cluster name
  GKE_ZONE: us-central1  # cluster zone
  IMAGE: micro # image name
  IMAGE_TAG: blue # image tag
  GAR_ZONE: us-east1 # artifact registry zone
  GAR_REPO:  cloudshirtpermanentrepository # artifact registry repository

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SECRETS_GCP_SA_KEY }}'

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: Docker configuration
      run: |-
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_ZONE-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
              docker build -t cloudshirt-web -f src/Web/Dockerfile .
              docker build -t cloudshirt-api -f src/PublicApi/Dockerfile .
              docker tag cloudshirt-web us-east1-docker.pkg.dev/plucky-balm-450118-b9/cloudshirtpermanentrepository/cloudshirt-web:latest
              docker tag cloudshirt-api us-east1-docker.pkg.dev/plucky-balm-450118-b9/cloudshirtpermanentrepository/cloudshirt-api:latest
              
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
              docker push us-east1-docker.pkg.dev/plucky-balm-450118-b9/cloudshirtpermanentrepository/cloudshirt-api:latest
              docker push us-east1-docker.pkg.dev/plucky-balm-450118-b9/cloudshirtpermanentrepository/cloudshirt-web:latest

